let containerGame = document.getElementById("container_game");
let terrain = document.createElement("div");
terrain.style.width = "600px";
terrain.style.height = "600px";
terrain.style.position = "relative";
terrain.style.margin = "0 auto";
terrain.style.backgroundRepeat = "repeat";
terrain.style.backgroundSize = "10% 10%";
terrain.style.backgroundImage = "url('img/ground.svg')";
containerGame.appendChild(terrain);